// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1vyxk-1Br_olpUhjU8BbbHOaX3kA9VEM',
    appId: '1:625692464997:android:cfcdec58231ba356ba738c',
    messagingSenderId: '625692464997',
    projectId: 'fir-auth-methods-64d3b',
    storageBucket: 'fir-auth-methods-64d3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMpHOjl_GXXEhtHc8Tmj625WKjYeqQ4Fk',
    appId: '1:625692464997:ios:5f261b1cc3972f0aba738c',
    messagingSenderId: '625692464997',
    projectId: 'fir-auth-methods-64d3b',
    storageBucket: 'fir-auth-methods-64d3b.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseMethods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWpzJXsUhIvQzViaxOICpI38XT0aF8P9E',
    appId: '1:625692464997:web:384f8887154a128dba738c',
    messagingSenderId: '625692464997',
    projectId: 'fir-auth-methods-64d3b',
    authDomain: 'fir-auth-methods-64d3b.firebaseapp.com',
    storageBucket: 'fir-auth-methods-64d3b.appspot.com',
  );
}
